### ISSUE TITLE
Question on the OS level cgroup config

### ISSUE THREAD

**Issue by kunalsumbly** [caarlos0/java-docker-cgroups#1]
Thanks for this,  can you also share the cgroup JVM defaults which are being set in at your OS level.

**Comment by caarlos0** [comment]
its just what is in the entrypoint (https://github.com/caarlos0/java-docker-cgroups/blob/master/entrypoint.sh#L2)

no config at the host level at all..

<blockquote><img src="https://avatars1.githubusercontent.com/u/245435?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/caarlos0/java-docker-cgroups">caarlos0/java-docker-cgroups</a></strong></div><div>Testing the jre 1.8.0_141 on docker limiting resources with cgroups - caarlos0/java-docker-cgroups</div></blockquote>
